### ISSUE TITLE
Does not work on 1.17.1 Paper (Java 16)

### ISSUE THREAD

**Issue by Quallysus** [Summiner/ServerPatches#5] opened 2024-02-18 15:30 UTC
The plugin simply does not load on 1.17.1 Paper (Java 16), please add support for this, as older versions need this plugin the most.

**Comment by Summiner** [comment] 2024-02-18 18:04
Could you please provide the error you are getting when loading the plugin? A simple fix for this would likely be switching to java 17

**Comment by Misjudgments** [comment] 2024-02-19 14:47
> Could you please provide the error you are getting when loading the plugin? A simple fix for this would likely be switching to java 17

i'm not the author but if one tries to put it into a 1.17.1 server this is the error:
[14:44:10 INFO]: Misjudgments issued server command: /serverpatches:spatches
[14:44:10 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'serverpatches:spatches' in plugin ServerPatches v1.0.2-HOTFIX
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at summiner.serverpatches.utils.Command.onCommand(Command.java:20) ~[Server-Patches.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-411]
	... 21 more

**Comment by Quallysus** [comment] 2024-02-19 19:14
For some reason i cannot load it with plugman anymore but when i was able to, it was a java class warning, saying it only goes up to 60 or something... not sure if that helps lol

**Comment by Summiner** [comment] 2024-02-20 22:40
added java 16 support in https://github.com/Summiner/ServerPatches/releases/tag/V1.0.3-release

**Closed by Summiner** 2024-02-20 22:40 UTC
Labels: Feature
