### ISSUE TITLE
ViaVersion

### ISSUE THREAD

**Issue by cL3v3r47** [Summiner/ServerPatches#15] opened 2024-04-29 18:41 UTC
It has console errors on the latest ViaVersion update

**Comment by cL3v3r47** [comment] 2024-04-29 18:45
[packetevents] Unable to grab ViaVersion client version for player!

**Comment by Summiner** [comment] 2024-04-29 20:06
Duplicate of https://github.com/Summiner/ServerPatches/issues/14

**Closed by Summiner** 2024-04-29 20:06 UTC
